### ISSUE TITLE
 Consolidate Duplicate Code in Social Media Authentication Functions (File: passport.middleware.js)

### ISSUE THREAD

**Issue by BrosG** [Atayen/API_NODE_SATT#216]
Functions such as handleSocialMediaSignin and the associated methods for different social media sign-ins contain a lot of similar code. There's an opportunity to consolidate this code into shared functions or create a generic function that can handle different social media sign-ins. This would help in reducing the code redundancy and improve the maintainability of the codebase.

**Comment by ksibisamir** [comment]
Fixed #218
