### ISSUE TITLE
Critical vulnerability!!

### ISSUE THREAD

**Issue by yesh2406** [Atayen/API_NODE_SATT#4]
Hey there,

I found a very critical vulnerability in satt wallet, Where I'm able to take over anyone's satt account. Please reply here so we can discuss.

**Comment by HamdiBenK** [comment]
hello, 

Tell me about it

**Comment by yesh2406** [comment]
Fixed!

**Comment by yesh2406** [comment]
@HamdiBenK Hi, Any updates on this?

**Comment by yesh2406** [comment]
Hello, any updates on this?
